export default {
    namespace: 'voucher',
    state: {
        vouchers: [
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher Đây là mô tả con bò voucher Đây là mô tả con bò voucher Đây là mô tả con bò voucher Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
            {
                id:1,
                name: 'Voucher con bò',
                description: 'Đây là mô tả con bò voucher',
                valid_date: '20-4-2022',
                expiration_date: '21-4-2022',
                value: 'value',
                min_purchase: 1000,
            },
        ]
    }
}